package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doPset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doPset extends BaseT1doPset<T1doPset> {
	public static final T1doPset dao = new T1doPset().dao();
}
