package com.demo.common.model;

import com.demo.common.model.base.BaseTRegCompanyDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRegCompanyDept extends BaseTRegCompanyDept<TRegCompanyDept> {
	public static final TRegCompanyDept dao = new TRegCompanyDept().dao();
}
