package com.luqi.common.model;

import java.util.List;

import com.alibaba.fastjson.JSONObject;
import com.luqi.common.model.base.BaseT1doBoardTaskReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doBoardTaskReport extends BaseT1doBoardTaskReport<T1doBoardTaskReport> {
	public static final T1doBoardTaskReport dao = new T1doBoardTaskReport().dao();
	//获得整份报告的总结 
	public static List<T1doBoardTaskReport> getSummary(JSONObject json) {
		
		return dao.find("select * from t_1do_board_task_report where DATE=? "
				+ "and PROJECT_ID=?",json.getString("date"),json.getLongValue("projectId"));
	}
	public static T1doBoardTaskReport getT1doBoardTaskReport(T1doBoardTaskReport r) {
		return dao.findFirst("select * from t_1do_board_task_report where DATE=? "
				+ "and PROJECT_ID=? and NUMBER=?",r.getDATE(),r.getProjectId(),r.getNUMBER());
		
	}
}
