package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doUser extends BaseT1doUser<T1doUser> {
	public static final T1doUser dao = new T1doUser().dao();
	/*
	 2018年8月14日下午1:33:10 方升群
	*/
	public static T1doUser getUser(String loginName) {
		return T1doUser.dao.findFirst("SELECT * from t_1do_user WHERE SHOW_ID=? ",loginName);			
	}
	
}
