package com.luqi.common.model;

import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.luqi.common.model.base.BaseT1doBoardTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doBoardTask extends BaseT1doBoardTask<T1doBoardTask> {
	public static final T1doBoardTask dao = new T1doBoardTask().dao();
	//获得项目完整日期
	public static List<T1doBoardTask> getBoardTask(JSONObject json) {
		
		/*
		 * return dao.
		 * find("select ID,TASK,DATE,PROJECT_ID,COMPLETION,ifnull(PRINCIPLE,'数据局') PRINCIPLE,"
		 * +
		 * "PRINCIPLE_SHOW_ID,PLANNED_DATE,DATA,ITEM_ID,ATEMP,BTEMP from t_1do_board_task  where"
		 * + " DATE=? and PROJECT_ID=?",json.getString("date"),json.getLongValue(
		 * "projectId"));
		 */
		return dao.find("select a.ID,a.TASK,a.DATE,a.PROJECT_ID,a.COMPLETION,ifnull(a.PRINCIPLE,'数据局') PRINCIPLE,\n" + 
				"				a.PRINCIPLE_SHOW_ID,a.PLANNED_DATE,a.PLANNED_TIME,a.DATA,a.ITEM_ID,a.ATEMP,a.BTEMP ,ifnull(b.IS_OPEN,0) IS_OPEN from t_1do_board_task a left join\n" + 
				"				(select true IS_OPEN,ITEM_ID,DATE from t_1do_board_task_1do  GROUP BY ITEM_ID,DATE) b\n" + 
				"			on a.ITEM_ID=b.ITEM_ID and a.DATE=b.DATE	where\n" + 
				"				 a.DATE=? and a.PROJECT_ID=?",json.getString("date"),json.getLongValue("projectId"));
	}

	/**
	 * 获取项目进度
	 * @return
	 */
	public static List<Record> getProjectProgress(long projectId, String date) {
		String sql = "SELECT a.*,tr.`CONTENT` evaluate FROM (SELECT t.`ID`,t.`TASK`,t.`PLANNED_DATE`,r.`CONTENT`,d.`D_NAME`," +
				"r.`COMPANY`,GROUP_CONCAT(distinct u.`U_TRUE_NAME`) principle,t.`COMPLETION` completion " +
				"FROM `t_1do_board_task` t,`t_1do_board_daliy_report` r,`t_reg_company_dept` d,`t_1do_project_stakeholder` s, `t_reg_user` u " +
				"WHERE r.`PROJECT_ID` = ? and r.`DATE`=? and t.`ITEM_ID`=r.`TASK_ID` and t.`DATE`=r.`DATE` and r.`COMPANY` = d.`SHOW_ID` " +
				"and t.`PROJECT_ID`=s.`PROJECT_ID` and r.`COMPANY` = s.`COMPANY` and u.`SHOW_ID` = s.`O_USER` " +
				"GROUP BY s.`COMPANY`,r.ID) a  LEFT JOIN `t_1do_board_task_remarks` tr ON a.`ID` =tr.`TASK_ID` " +
				"and a.`COMPANY` = tr.`COMPANY_ID` ORDER BY a.ID";
		return Db.find(sql,projectId,date);
	}

	public static T1doBoardTask getTask(Date date, Long ITEM_ID) {
		return dao.findFirst("select * from t_1do_board_task where DATE=? and ITEM_ID=?",date,ITEM_ID);
	}
}
