package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doBoardTaskRemarks;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doBoardTaskRemarks extends BaseT1doBoardTaskRemarks<T1doBoardTaskRemarks> {
	public static final T1doBoardTaskRemarks dao = new T1doBoardTaskRemarks().dao();

	/**
	 * 根据任务id，公司ShowId查询对象
	 * @param taskId
	 * @param companyShowId
	 * @return
	 */
	public static T1doBoardTaskRemarks getInstance(long taskId, String companyShowId) {
		String sql = "SELECT * FROM `t_1do_board_task_remarks` WHERE `TASK_ID` = ? and `COMPANY_ID` = ?";
		return dao.findFirst(sql, taskId, companyShowId);
	}

}
