package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doBoardUpdateLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doBoardUpdateLog extends BaseT1doBoardUpdateLog<T1doBoardUpdateLog> {
	public static final T1doBoardUpdateLog dao = new T1doBoardUpdateLog().dao();

}
