package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doYscg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doYscg extends BaseT1doYscg<T1doYscg> {
	public static final T1doYscg dao = new T1doYscg().dao();
	
	public static int getT1doYscg(String name,int type) {
		T1doYscg y=dao.findFirst("select * from t_1do_yscg where name=? and type=?",name,type);
		if(y==null)
			return 0;
		return y.getCode();
	}
}
