package com.luqi.common.model;

import com.luqi.common.model.base.BaseTRegCompanyApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRegCompanyApp extends BaseTRegCompanyApp<TRegCompanyApp> {
	public static final TRegCompanyApp dao = new TRegCompanyApp().dao();
}
