package com.luqi.common.model;

import com.luqi.common.model.base.BaseTRegCompanyDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRegCompanyDept extends BaseTRegCompanyDept<TRegCompanyDept> {
	public static final TRegCompanyDept dao = new TRegCompanyDept().dao();

	/**
	 * 根据用户showId获取对象
	 *
	 * @param userShowId
	 * @return
	 */
	public static TRegCompanyDept getInstanceByUser(String userShowId) {
		String sql = "select d.`SHOW_ID`,d.`D_PATH` FROM `t_reg_company_dept` d, `t_reg_user_dept` ud WHERE ud.`U_DEPT_ID` = d.`SHOW_ID` and ud.`U_NAME` = ?";
		return dao.findFirst(sql, userShowId);
	}
}
