package com.luqi.common.model;

import com.luqi.common.model.base.BaseTRegUserDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRegUserDept extends BaseTRegUserDept<TRegUserDept> {
	public static final TRegUserDept dao = new TRegUserDept().dao();
}
