package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doIp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doIp extends BaseT1doIp<T1doIp> {
	public static final T1doIp dao = new T1doIp().dao();
}
