package com.luqi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseT1doWeight<M extends BaseT1doWeight<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Long ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public M setLABEL(java.lang.String LABEL) {
		set("LABEL", LABEL);
		return (M)this;
	}
	
	public java.lang.String getLABEL() {
		return getStr("LABEL");
	}

	public M setWEIGHT(java.lang.Integer WEIGHT) {
		set("WEIGHT", WEIGHT);
		return (M)this;
	}
	
	public java.lang.Integer getWEIGHT() {
		return getInt("WEIGHT");
	}

}
