package com.demo.common.model;

import com.demo.common.model.base.BaseT1doUrgeWebsocket;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doUrgeWebsocket extends BaseT1doUrgeWebsocket<T1doUrgeWebsocket> {
	public static final T1doUrgeWebsocket dao = new T1doUrgeWebsocket().dao();
	/*
	 2019年2月22日 coco 注解：
	*/
	public static int  updateOnline(String sessionid) {
		 return Db.update("update t_1do_urge_websocket set isOnline=false where sessionid=?",sessionid);
	}
}
