package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doKeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doKeyword extends BaseT1doKeyword<T1doKeyword> {
	public static final T1doKeyword dao = new T1doKeyword().dao();
}
