package com.demo.common.model;

import com.demo.common.model.base.BaseT1doSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doSet extends BaseT1doSet<T1doSet> {
	public static final T1doSet dao = new T1doSet().dao();
}
