package com.demo.common.model;

import java.util.Date;

import com.demo.common.model.base.BaseT1doLog;
import com.demo.util.StrUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doLog extends BaseT1doLog<T1doLog> {
	public static final T1doLog dao = new T1doLog().dao();
	
	/*
	 2018年8月14日上午11:05:29 方升群 // 查询该人是否查看过 true没有看过，false看过
	*/
	public static boolean getisLook(String showid,String loginName) {
		return T1doLog.dao.findFirst("select * from t_1do_log where SHOW_ID=? and O_USER =? and log_type=2",showid,loginName)==null?true:false;
		
	}
	/*
	 2018年8月31日上午11:16:12 方升群
	*/
	public static boolean saveLog(String SHOW_ID,String O_USER,String O_USER_NAME,String log,int log_type,String content) {
		if(StrUtil.isNotEmpty(content)){
			return new T1doLog().setShowId(SHOW_ID).setOpTime(new Date()).setOUser(O_USER).setOUserName(O_USER_NAME).setLog(log).setContent(content).setLogType(log_type).save();
        }
		return new T1doLog().setShowId(SHOW_ID).setOpTime(new Date()).setOUser(O_USER).setOUserName(O_USER_NAME).setLog(log).setLogType(log_type).save();

	}
}
