package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseT1doRelationFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doRelationFeedback extends BaseT1doRelationFeedback<T1doRelationFeedback> {
	public static final T1doRelationFeedback dao = new T1doRelationFeedback().dao();
	
	/*
	 2019年5月5日 coco 注解：保存反馈关联
	*/
	public static void saveRF(String showId,Integer FBID,Integer SIMILARITY) {
		new T1doRelationFeedback().setShowId(showId).setFBID(FBID).setSIMILARITY(SIMILARITY).save();
	}

	public static List<T1doRelationFeedback> selectRelation(String showid, String sql) {
		return dao.find("select a.ID,a.SHOW_ID,a.O_USER,a.O_USER_NAME,unix_timestamp(a.FB_TIME)*1000 FB_TIME,a.FBCONTENT,b.SIMILARITY,b.ID RFID,b.type "
				+" from t_1do_feedback a,t_1do_relation_feedback b,t_1do_base c"
		        +" where a.ID=b.FBID and b.SHOW_ID=c.SHOW_ID and c.FEEDBACK_SIMILARITY<b.SIMILARITY"
		        +" and b.SHOW_ID=? and b.type!=2 and a.FB_TYPE!=7 and a.isoverdue=1"+sql+" ORDER BY SIMILARITY desc",showid);
		
	}
	
}
