package com.luqi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseT1doFbtype<M extends BaseT1doFbtype<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setOTypeId(java.lang.String oTypeId) {
		set("O_TYPE_ID", oTypeId);
		return (M)this;
	}
	
	public java.lang.String getOTypeId() {
		return getStr("O_TYPE_ID");
	}

	public M setOTypeName(java.lang.String oTypeName) {
		set("O_TYPE_NAME", oTypeName);
		return (M)this;
	}
	
	public java.lang.String getOTypeName() {
		return getStr("O_TYPE_NAME");
	}

	public M setOParentId(java.lang.String oParentId) {
		set("O_PARENT_ID", oParentId);
		return (M)this;
	}
	
	public java.lang.String getOParentId() {
		return getStr("O_PARENT_ID");
	}

}
