package com.luqi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseT1doProject<M extends BaseT1doProject<M>> extends Model<M> implements IBean {

	public M setItemId(java.lang.Long itemId) {
		set("ITEM_ID", itemId);
		return (M)this;
	}
	
	public java.lang.Long getItemId() {
		return getLong("ITEM_ID");
	}

	public M setOCreateTime(java.util.Date oCreateTime) {
		set("O_CREATE_TIME", oCreateTime);
		return (M)this;
	}
	
	public java.util.Date getOCreateTime() {
		return get("O_CREATE_TIME");
	}

	public M setOFinishTime(java.util.Date oFinishTime) {
		set("O_FINISH_TIME", oFinishTime);
		return (M)this;
	}
	
	public java.util.Date getOFinishTime() {
		return get("O_FINISH_TIME");
	}

	public M setIsFinish(java.lang.Boolean isFinish) {
		set("IS_FINISH", isFinish);
		return (M)this;
	}
	
	public java.lang.Boolean getIsFinish() {
		return get("IS_FINISH");
	}

	public M setIsKey(java.lang.Boolean isKey) {
		set("IS_KEY", isKey);
		return (M)this;
	}
	
	public java.lang.Boolean getIsKey() {
		return get("IS_KEY");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setGroupName(java.lang.String groupName) {
		set("GROUP_NAME", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("GROUP_NAME");
	}

	public M setCrateUser(java.lang.String crateUser) {
		set("CRATE_USER", crateUser);
		return (M)this;
	}
	
	public java.lang.String getCrateUser() {
		return getStr("CRATE_USER");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("UPDATE_TIME", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("UPDATE_TIME");
	}

	public M setGroupId(java.lang.String groupId) {
		set("GROUP_ID", groupId);
		return (M)this;
	}
	
	public java.lang.String getGroupId() {
		return getStr("GROUP_ID");
	}

	public M setIsDeleted(java.lang.Boolean isDeleted) {
		set("IS_DELETED", isDeleted);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDeleted() {
		return get("IS_DELETED");
	}

}
