package com.luqi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseT1doBoard<M extends BaseT1doBoard<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Long ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Long getID() {
		return getLong("ID");
	}

	public M setParentId(java.lang.Long parentId) {
		set("PARENT_ID", parentId);
		return (M)this;
	}
	
	public java.lang.Long getParentId() {
		return getLong("PARENT_ID");
	}

	public M setItemName(java.lang.String itemName) {
		set("ITEM_NAME", itemName);
		return (M)this;
	}
	
	public java.lang.String getItemName() {
		return getStr("ITEM_NAME");
	}

	public M setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
		return (M)this;
	}
	
	public java.lang.Integer getTYPE() {
		return getInt("TYPE");
	}

	public M setCOMPLETION(java.lang.String COMPLETION) {
		set("COMPLETION", COMPLETION);
		return (M)this;
	}
	
	public java.lang.String getCOMPLETION() {
		return getStr("COMPLETION");
	}

	public M setFinishDate(java.util.Date finishDate) {
		set("FINISH_DATE", finishDate);
		return (M)this;
	}
	
	public java.util.Date getFinishDate() {
		return get("FINISH_DATE");
	}

}
