package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doBoardLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doBoardLog extends BaseT1doBoardLog<T1doBoardLog> {
	public static final T1doBoardLog dao = new T1doBoardLog().dao();

	/**
	 * 插入看板历史记录
	 * @param t1doBoard
	 * @param userShowId 用户showId
	 * @param type 类型1新增2修改3删除
	 */
	public static void insertT1doBoardLog(T1doBoard t1doBoard,String userShowId,int type) {
		T1doBoardLog t1doBoardLog = new T1doBoardLog();
		t1doBoardLog.setItemId(t1doBoard.getID());
		t1doBoardLog.setItemName(t1doBoard.getItemName());
		t1doBoardLog.setParentId(t1doBoard.getParentId());
		t1doBoardLog.setOUser(userShowId);
		t1doBoardLog.setTYPE(type);
		t1doBoardLog.save();
	}
}
