package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("approval", "id", Approval.class);
		arp.addMapping("t_1do_attr", "ID", T1doAttr.class);
		arp.addMapping("t_1do_base", "ID", T1doBase.class);
		arp.addMapping("t_1do_eventtype", "ID", T1doEventtype.class);
		arp.addMapping("t_1do_fbtype", "ID", T1doFbtype.class);
		arp.addMapping("t_1do_feedback", "ID", T1doFeedback.class);
		arp.addMapping("t_1do_fw", "ID", T1doFw.class);
		arp.addMapping("t_1do_fwpstatus", "ID", T1doFwpstatus.class);
		arp.addMapping("t_1do_label", "ID", T1doLabel.class);
		arp.addMapping("t_1do_label_feedback", "ID", T1doLabelFeedback.class);
		arp.addMapping("t_1do_label_record", "ID", T1doLabelRecord.class);
		arp.addMapping("t_1do_log", "ID", T1doLog.class);
		arp.addMapping("t_1do_order", "id", T1doOrder.class);
		arp.addMapping("t_1do_pset", "ID", T1doPset.class);
		arp.addMapping("t_1do_pstatus", "ID", T1doPstatus.class);
		arp.addMapping("t_1do_record", "ID", T1doRecord.class);
		arp.addMapping("t_1do_relation", "ID", T1doRelation.class);
		arp.addMapping("t_1do_relation_feedback", "ID", T1doRelationFeedback.class);
		arp.addMapping("t_1do_relation_record", "ID", T1doRelationRecord.class);
		arp.addMapping("t_1do_set", "ID", T1doSet.class);
		arp.addMapping("t_1do_status", "ID", T1doStatus.class);
		arp.addMapping("t_1do_temp", "ID", T1doTemp.class);
		arp.addMapping("t_1do_type", "ID", T1doType.class);
		arp.addMapping("t_1do_urge_websocket", "id", T1doUrgeWebsocket.class);
		arp.addMapping("t_1do_user", "ID", T1doUser.class);
		arp.addMapping("t_reg_company", "ID", TRegCompany.class);
		arp.addMapping("t_reg_company_dept", "ID", TRegCompanyDept.class);
		arp.addMapping("t_reg_user", "ID", TRegUser.class);
		arp.addMapping("t_reg_user_dept", "ID", TRegUserDept.class);
		arp.addMapping("websocket", "id", Websocket.class);
	}
}

