package com.demo.common.model;

import com.demo.common.model.base.BaseT1doEventtype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doEventtype extends BaseT1doEventtype<T1doEventtype> {
	public static final T1doEventtype dao = new T1doEventtype().dao();
}
