package com.demo.common.model;

import com.demo.common.model.base.BaseT1doOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doOrder extends BaseT1doOrder<T1doOrder> {
	public static final T1doOrder dao = new T1doOrder().dao();
	/*
	 2018年8月15日上午10:29:02 方升群
	*/
	public static T1doOrder getT1doOrder(String showid,String loginName,int type) {
		return 	T1doOrder.dao.findFirst("select * from t_1do_order where SHOW_ID=? and useraccount=? and type=?",showid,loginName,type);

	}
}
