package com.demo.common.model;

import com.demo.common.model.base.BaseT1doStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doStatus extends BaseT1doStatus<T1doStatus> {
	public static final T1doStatus dao = new T1doStatus().dao();
}
