package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseT1doRecord;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doRecord extends BaseT1doRecord<T1doRecord> {
	public static final T1doRecord dao = new T1doRecord().dao();
	/*
	 2019年5月9日 coco 注解：
	*/
	public static Long getid() {
		T1doRecord r=T1doRecord.dao.findFirst("select max(RECORDID) RECORDID from t_1do_record");
		return r.getRECORDID();
	}
	/*
	 2019年5月8日 coco 注解：
	*/
	public static void batchSave() {
		List<T1doRecord> list=dao.use("record").find("select a.ExecutiveAccount ACCOUNT,a.ExecutiveName NAME,"
				+ "b.Process RECORD,b.id RECORDID,a.AddTime CREATETIME from WorkReport a,"
				+ "WorkRecord b where a.id=b.WorkReportID ");
		Db.batchSave(list, 100);
	}
	/*
	 2019年5月8日 coco 注解：定时查询数据
	 */
	public static void batchSaveForTime() {
		//T1doRecord r=T1doRecord.dao.findFirst("select max(RECORDID) RECORDID from t_1do_record");
		/*List<T1doRecord> list=dao.use("record").find("select a.ExecutiveAccount ACCOUNT,a.ExecutiveName NAME,"
				+ "b.Process RECORD,b.id RECORDID,a.AddTime CREATETIME from WorkReport a,"
				+ "WorkRecord b where a.id=b.WorkReportID and b.id>?",getid());*/
		List<Record> records=Db.use("record").find("select a.ExecutiveAccount ACCOUNT,a.ExecutiveName NAME,"
				+ "b.Process RECORD,b.id RECORDID,a.AddTime CREATETIME from WorkReport a,"
				+ "WorkRecord b where a.id=b.WorkReportID and b.id>?",getid());
		System.out.println("同步日志程序查询到新的日志："+records.size()+"条");
		//Db.batchSave(list, 100);
		Db.batchSave("t_1do_record", records, 100);
		records.forEach(t->{
			T1doLabelRecord.saveAllLabel1(t);
			
		});
		//T1doRecord r1=T1doRecord.dao.use("").findFirst("select max(RECORDID) RECORDID from t_1do_record");

	}
}
