package com.demo.common.model;

import com.demo.common.model.base.BaseT1doType;
import com.demo.util.IDUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doType extends BaseT1doType<T1doType> {
	public static final T1doType dao = new T1doType().dao();
	
	/*
	 2018年6月21日 方升群  保存T1doType
	*/
	public static boolean save(String meg) {
		return new T1doType().setOTypeId(IDUtil.getUid()).setOTypeName(meg).setOParentId("0").save();
	}
}
