package com.demo.common.model;

import com.demo.common.model.base.BaseT1doTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doTemp extends BaseT1doTemp<T1doTemp> {
	public static final T1doTemp dao = new T1doTemp().dao();
}
