package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseT1doPstatus;
import com.demo.util.StrUtil;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doPstatus extends BaseT1doPstatus<T1doPstatus> {
	public static final T1doPstatus dao = new T1doPstatus().dao();
	public List<T1doFeedback> getIdoFeedbacks44() {
		return T1doFeedback.dao.find("select  O_USER_NAME from t_1do_feedback where SHOW_ID=? and FB_TYPE=4",get("SHOW_ID"));
	}
	/*
	 2018年6月22日下午4:01:48 方升群
	*/
	public static void saveIdoPstatus(String showID,String...users) {
		int i=1;
		for(String user:users){
			String[] sonUsers=user.split(";");
				for(String sonUser:sonUsers){
					new T1doPstatus().setShowId(showID).setOUser(sonUser).setOStatus(i).setUserType(i).save();
					new T1doPset().setShowId(showID).setOUser(sonUser).setEventType("1;2;3;4;5;6;").setUserType(i).save();
				}
			i++;
		}
	}
	public static void saveIdoPstatus1(String showID,String[] users,String[] usernames) {
			for (int j = 0; j < users.length; j++) {
				if(StrUtil.isEmpty(users[j])){
					break;
				}
			String[] sonUsers=users[j].split(";");
			String[] sonUsernames=usernames[j].split(";");
			for (int i = 0; i < sonUsers.length; i++) {
				new T1doPstatus().setShowId(showID).setOUser(sonUsers[i]).setOUserName(sonUsernames[i]).setOStatus(j+1).setUserType(j+1).save();
				//new T1doPset().setShowId(showID).setOUser(sonUsers[i]).setEventType("1;2;3;4;5;6;").setUserType(j+1).save();
			}
			
		}
	}
	
	/*
	 2018年6月25日下午2:08:58 方升群    //获得发起人/受理人1do状态为1已送达2/3.待处理/4.处理中并且   1do和人员订阅事件都包含1.送达
	*/
	public List<Record> getRecords() {
		return Db.find("select b.SHOW_ID,b.O_TITLE,b.O_DESCRIBE,b.O_EXECUTOR_NAME,t.O_TYPE_NAME,p.O_STATUS,p.USER_TYPE from t_1do_base b,t_1do_pstatus p,t_1do_type t where p.O_USER=? " 
+"and p.USER_TYPE !=2 and b.SHOW_ID=p.SHOW_ID and b.O_TYPE_ID=t.O_TYPE_ID  and b.O_IS_DELETED=1 order by SHOW_ID desc",get("O_USER"));
	}
	
	/*
	 2018年8月9日上午11:15:06 方升群  //是否查看
	*/
	public int getIsLook() {
		Record r=Db.findFirst("select * from t_1do_log where SHOW_ID=? and O_USER=?",get("SHOW_ID"),get("O_USER"));
		return r==null?2:1;
	}
	/*
	 2018年8月10日上午9:46:00 方升群 //查询是否是参与人或发起人
	*/
	public static T1doPstatus getCustomerOrExecutor(String showid,String loginName,int i) {
		return T1doPstatus.dao.findFirst("select * from t_1do_pstatus where SHOW_ID=? and O_USER =? and USER_TYPE=?",showid,loginName,i);
	}
	//查询用户角色
	public static T1doPstatus getUser(String showid,String loginName) {
		return T1doPstatus.dao.findFirst("select * from t_1do_pstatus where SHOW_ID=? and O_USER =? and USER_TYPE!=2 and isDelete=1 ",showid,loginName);
	}
	
}
