package com.demo.common.model;

import java.util.ArrayList;
import java.util.List;

import com.alibaba.fastjson.JSONObject;
import com.demo.common.model.base.BaseTRegUser;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRegUser extends BaseTRegUser<TRegUser> {
	public static final TRegUser dao = new TRegUser().dao();
	
	/*
	 2018年11月28日 coco 注解：
	*/
	public static JSONObject getUser(JSONObject json) {
		
		Record r= Db.findFirst("SELECT SHOW_ID ,LAST_LOGIN_TOKEN ,C_SHOW_ID FROM t_reg_user  where "
				+ "U_MAIL=? or U_LOGIN_NAME=?",json.getString("useraccount"),json.getString("useraccount"));		
		if(r!=null){
			List<TRegCompanyDept> list =TRegCompanyDept.dao.find("select b.SHOW_ID,b.D_NAME from t_reg_user_dept a, t_reg_company_dept b where a.U_DEPT_ID=b.SHOW_ID and a.U_NAME=?",r.getStr("SHOW_ID"));
			List<String> lists=new ArrayList<String>();
			List<String> lists1=new ArrayList<String>();
			for (TRegCompanyDept t : list) {		
				lists.add(t.getShowId());		
				lists1.add(t.getDName());
			}
			json.put("U_DEPT_ID", lists);
			json.put("D_NAME", lists1);
			json.put("loginName", r.getStr("SHOW_ID"));
			json.put("LoginToken", r.getStr("LAST_LOGIN_TOKEN"));
			json.put("cShowId", r.getStr("C_SHOW_ID"));			
			return json;
		}
		
		return null;
	}
	/*
	 2018年11月28日 coco 注解：
	*/
	public static void saveUser(JSONObject json2) {
		new TRegUser().setShowId(json2.getString("loginName")).setULoginName(json2.getString("useraccount")).setCShowId(json2.getString("cShowId")).setUTrueName(json2.getString("username"))
		.setLastLoginToken(json2.getString("LoginToken")).setUName(json2.getString("loginName")).save();
		@SuppressWarnings("unchecked")
		List<String> arr=(List<String>) json2.get("D_NAME");
		@SuppressWarnings("unchecked")
		List<String> arr1=(List<String>) json2.get("U_DEPT_ID");
		for (int i = 0; i < arr1.size(); i++) {
			new TRegUserDept().setUName(json2.getString("loginName")).setUDeptId(arr1.get(i)).setCShowId("b5WJZ1bRLDCb7x2B").save();
			Record r=Db.findFirst("select * from t_reg_company_dept where show_id=?",arr1.get(i));
			if(r==null){
				new TRegCompanyDept().setShowId(arr1.get(i)).setDName(arr.get(i)).save();
			}
			
		}
		
	}
}
