package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doFbtype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doFbtype extends BaseT1doFbtype<T1doFbtype> {
	public static final T1doFbtype dao = new T1doFbtype().dao();
}
