package com.demo.common.model;

import com.demo.common.model.base.BaseT1doFwpstatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doFwpstatus extends BaseT1doFwpstatus<T1doFwpstatus> {
	public static final T1doFwpstatus dao = new T1doFwpstatus().dao();
}
