package com.luqi.common.model;

import com.luqi.common.model.base.BaseTempab;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tempab extends BaseTempab<Tempab> {
	public static final Tempab dao = new Tempab().dao();
}
