package com.luqi.common.model;

import java.util.List;

import com.luqi.common.model.base.BaseT1doBoardTaskProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doBoardTaskProgress extends BaseT1doBoardTaskProgress<T1doBoardTaskProgress> {
	public static final T1doBoardTaskProgress dao = new T1doBoardTaskProgress().dao();

	/**
	 * 获取项目的进展列表
	 * @param projectId
	 * @return
	 */
	public static List<T1doBoardTaskProgress> getProgressListByProjectId(long projectId) {
		String sql = "SELECT * FROM `t_1do_board_task_progress` WHERE `PROJECT_ID` = ?";
		return dao.find(sql, projectId);
	}
}
