package com.luqi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseT1doEventtype<M extends BaseT1doEventtype<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setEventType(java.lang.Integer eventType) {
		set("EVENT_TYPE", eventType);
		return (M)this;
	}
	
	public java.lang.Integer getEventType() {
		return getInt("EVENT_TYPE");
	}

	public M setEventTypeName(java.lang.String eventTypeName) {
		set("EVENT_TYPE_NAME", eventTypeName);
		return (M)this;
	}
	
	public java.lang.String getEventTypeName() {
		return getStr("EVENT_TYPE_NAME");
	}

}
