package com.demo.common.model;

import com.demo.common.model.base.BaseApproval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Approval extends BaseApproval<Approval> {
	public static final Approval dao = new Approval().dao();
}
