package com.demo.common.model;

import com.demo.common.model.base.BaseTRegCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TRegCompany extends BaseTRegCompany<TRegCompany> {
	public static final TRegCompany dao = new TRegCompany().dao();
}
