package com.luqi.common.model;

import com.luqi.common.model.base.BaseT1doCall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T1doCall extends BaseT1doCall<T1doCall> {
	public static final T1doCall dao = new T1doCall().dao();
}
